# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: arduino-memory-alloc

{% if GIT_DESCRIBE_NUMBER > '0' %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.post{{ GIT_DESCRIBE_NUMBER }}
{% else %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.0
{% endif %}

requirements:
  build:
    - arduino-aligned-alloc
    - arduino-linked-list >=1.2.3

  run:
    - arduino-aligned-alloc
    - arduino-linked-list >=1.2.3


build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

about:
  home: https://github.com/sci-bots/arduino-memory-alloc
  license: MIT
